"""CPU software attacks and arithmetic checks. Synthetic pixels are not expert labels."""
import base64
import copy
import hashlib
import io
import json
import time
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor
import httpx
import pytest
from fastapi.testclient import TestClient
from PIL import Image
from cizheng.api import create_app
from cizheng.agent import LocalModel
from cizheng.review_client import StepFunClient
from cizheng.store import uid, digest
from cizheng.risk_triage import calculate, DIMENSIONS, triage, material_context
from cizheng.device_capture import parse_multipart, IMAGE_LIMIT


@pytest.fixture
def service(tmp_path, monkeypatch):
    async def no_model(*a, **k):
        pytest.fail('Risk/device CPU feature must never call a model or external HTTP')
    monkeypatch.setattr(LocalModel,'complete',no_model)
    monkeypatch.setattr(StepFunClient,'review',no_model)
    monkeypatch.setattr(httpx.AsyncClient,'request',no_model)
    monkeypatch.delenv('CIZHENG_MODEL_URL',raising=False)
    app=create_app(tmp_path)
    with TestClient(app) as c:
        c.headers['X-Cizheng-Token']=c.get('/api/status').json()['session_token']
        yield c,app.state.store


def new(c):
    r=c.post('/api/cases',json={'request_id':uid('req'),'title':'协议测试，不是鉴定样本','question':'检查记录矛盾'})
    assert r.status_code==200
    return r.json()


def mut(case):
    return {'request_id':uid('req'),'expected_case_revision':case['revision']}


def image(color='white'):
    f=io.BytesIO();Image.new('RGB',(40,60),color).save(f,'PNG');return f.getvalue()


def photo(c,case,color='white'):
    raw=image(color)
    r=c.post('/api/cases/'+case['id']+'/evidence',json=mut(case)|{'filename':'test.png',
        'image_base64':base64.b64encode(raw).decode(),'view':'synthetic protocol pixels'})
    assert r.status_code==200
    return r.json()['case'],raw


def ref(case):
    m=case['media'][0]
    return {'kind':'media','id':m['id'],'sha256':m['sha256'],'locator':'whole original image'}


def session(c,case,**kwargs):
    r=c.post('/api/cases/'+case['id']+'/capture-sessions',json=mut(case)|{
        'device':{'kind':'glasses_bridge','label':'bridge protocol double'},**kwargs})
    assert r.status_code==201,r.text
    return r.json()


def capture_body(case,s,raw,**extra):
    return mut(case)|{'session_id':s['id'],'original_sha256':hashlib.sha256(raw).hexdigest(),
        'captured_at':datetime.now(timezone.utc).isoformat(),'operator':'protocol operator',
        'source':'synthetic test pixels','rights_declaration':'generated by test',
        'view':'overall','capture_role':'overall',**extra}


def upload(c,case,body,raw,filename='test.png'):
    return c.post('/api/cases/'+case['id']+'/device-captures',
        files={'metadata':(None,json.dumps(body),'application/json'),'file':(filename,raw,'image/png')})


def check(c,case,dimension='period',state='conflicting',**kwargs):
    r=c.post('/api/cases/'+case['id']+'/risk-checks',json=mut(case)|{
        'dimension':dimension,'state':state,'reason':'Exact saved evidence has a recorded disagreement',
        'next_evidence':'Compare original data and source','evidence':[ref(case)],**kwargs})
    return r


def fact(c,case,field,low=None,high=None,**kwargs):
    return c.post('/api/cases/'+case['id']+'/risk-facts',json=mut(case)|{
        'field':field,'value_min':low,'value_max':high,'statement':'Synthetic transcribed protocol statement',
        'evidence':[ref(case)],**kwargs})


def test_all_unknown_never_yields_false_reassurance(service):
    c,_=service;case=new(c)
    r=c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert r['indices']['conflict_index'] is None
    assert r['indices']['review_priority_index']==50
    assert r['indices']['coverage_weight']==0 and r['indices']['denominator_weight']==100
    assert not r['expert_calibrated'] and r['model_calls']==0 and not r['laya']['enabled']


def test_independent_formula_extremes_and_mixed_weight():
    def rows(state):return [{'dimension':d,'state':state} for d in DIMENSIONS]
    assert calculate(rows('conflicting'))['review_priority_index']==100
    assert calculate(rows('consistent'))['conflict_index']==0
    r=rows('unknown');r[0]['state']='conflicting';r[1]['state']='consistent'
    a=calculate(r)
    assert a['conflict_index']==20 and a['gap_weight']==65 and a['review_priority_index']==52.5
    assert a['coverage_weight']==35
    for invalid in [r+[{'dimension':'made_up','state':'consistent'}],r[:-1],r+[r[0]]]:
        with pytest.raises(ValueError):calculate(invalid)


@pytest.mark.parametrize('attack',['cross_case','wrong_hash','fake_kind','no_basis','unknown_dimension','nan'])
def test_check_attacks(service,attack):
    c,_=service;a,_=photo(c,new(c));b,_=photo(c,new(c),'red')
    changes={}
    if attack=='cross_case':changes['evidence']=[ref(b)]
    if attack=='wrong_hash':changes['evidence']=[ref(a)|{'sha256':'0'*64}]
    if attack=='fake_kind':changes['evidence']=[ref(a)|{'kind':'expert_certificate'}]
    if attack=='no_basis':changes['evidence']=[]
    if attack=='unknown_dimension':changes['dimension']='authenticity'
    if attack=='nan':changes['confidence']=.99
    before=c.get('/api/cases/'+a['id']).json()['case']
    r=check(c,a,**changes)
    assert r.status_code==422
    assert c.get('/api/cases/'+a['id']).json()['case']['revision']==before['revision']


def test_multiple_checks_dont_expire_each_other_but_material_change_does(service):
    c,_=service;case,_=photo(c,new(c))
    case=check(c,case).json()['case'];case=check(c,case,'kiln','consistent').json()['case']
    r=c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert r['indices']['conflict_index']==20 and r['indices']['coverage_weight']==35
    case,_=photo(c,case,'red')
    r=c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert r['indices']['conflict_index'] is None and len(r['history'])==2


def test_check_idempotency_and_stale_revision(service):
    c,_=service;case,_=photo(c,new(c));body=mut(case)|{'dimension':'period','state':'unknown',
        'reason':'unknown','next_evidence':'base photo','evidence':[]}
    path='/api/cases/'+case['id']+'/risk-checks';a=c.post(path,json=body)
    b=c.post(path,json=body);assert a.json()==b.json()
    assert c.post(path,json=body|{'reason':'other'}).status_code==409
    assert c.post(path,json=body|{'request_id':uid('req')}).status_code==409


def test_auto_numeric_conflicts_are_not_manual_scores(service):
    c,_=service;case,_=photo(c,new(c))
    case=fact(c,case,'height_mm',300,301).json()['case']
    case=fact(c,case,'height_mm',350,351).json()['case']
    r=c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert r['automatic_alerts'][0]['rule']=='same_property_disjoint_height_mm'
    assert r['indices']['conflict_index']==15 and r['indices']['review_priority_index']==57.5
    assert not r['professional_quality_verified']
    # An operator consistency statement cannot erase deterministic conflict.
    case=check(c,case,'capture','consistent').json()['case']
    assert c.get('/api/cases/'+case['id']+'/risk-triage').json()['indices']['conflict_index']==15


def test_temporal_and_identifier_conflicts(service):
    c,_=service;case,_=photo(c,new(c))
    case=fact(c,case,'production_year',1800,1850).json()['case']
    case=fact(c,case,'provenance_event_year',1700,1750).json()['case']
    for v in ['18.61.4','79.2.467']:
        case=fact(c,case,'object_identifier',identifier=v,namespace='Met inventory').json()['case']
    r=c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert {a['rule'] for a in r['automatic_alerts']}=={'event_precedes_declared_production','same_property_disjoint_object_identifier'}
    assert r['indices']['conflict_weight']==20  # Two provenance alarms count one fixed dimension.


def test_overlapping_ranges_and_different_namespaces_not_conflicts(service):
    c,_=service;case,_=photo(c,new(c))
    case=fact(c,case,'height_mm',300,310).json()['case']
    case=fact(c,case,'height_mm',305,315).json()['case']
    for v,n in [('a','museum'),('b','owner')]:
        case=fact(c,case,'object_identifier',identifier=v,namespace=n).json()['case']
    r=c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert not r['automatic_alerts'] and r['indices']['conflict_index'] is None


def test_supersession_cross_case_and_correction(service):
    c,_=service;case,_=photo(c,new(c))
    a=fact(c,case,'height_mm',300,301).json();case=a['case']
    b=fact(c,case,'height_mm',350,351).json();case=b['case']
    case=fact(c,case,'height_mm',300,301,supersedes=b['fact']['id']).json()['case']
    assert not c.get('/api/cases/'+case['id']+'/risk-triage').json()['automatic_alerts']
    other,_=photo(c,new(c),'red')
    assert fact(c,other,'height_mm',300,301,supersedes=a['fact']['id']).status_code==422


def test_foreign_and_stale_model_runs_never_contribute(service):
    c,store=service;a,_=photo(c,new(c));b,_=photo(c,new(c),'red')
    model={'id':'synthetic','case_id':b['id'],'case_revision':a['revision'],'state':'ready',
           'observations':[{'id':'o','media_id':a['media'][0]['id'],'region':[0,0,1,1]}],
           'assessment':{'claims':[{'dimension':'period','status':'conflicting','conflict':['o'],'reasoning_summary':'test'}]}}
    assert triage(store,a,model)['indices']['conflict_index'] is None
    model['assessment']['claims'][0]['conflict']=['not_present']
    assert triage(store,a,model)['indices']['conflict_index'] is None
    model['case_id']=a['id'];model['case_revision']-=1
    assert triage(store,a,model)['indices']['conflict_index'] is None


def test_device_roundtrip_original_and_duplicate_metadata(service):
    c,store=service;case=new(c);raw=image();s=session(c,case)
    body=capture_body(case,s,raw,sensors=[{'name':'height','value':12.5,'unit':'mm','source':'test declaration'}])
    a=upload(c,case,body,raw);assert a.status_code==201,a.text
    data=a.json();case=data['case'];receipt=data['receipt']
    assert store.blob(data['media']['id'])[1]==raw
    assert receipt['original_sha256']==hashlib.sha256(raw).hexdigest()
    assert receipt['sensors'][0]['unit']=='mm' and not receipt['sensor_inference_performed']
    assert not receipt['clock_verified'] and not receipt['vendor_authenticated']
    assert len(case['media'])==1 and not receipt['duplicate_original']
    b=upload(c,case,body,raw);assert b.json()==data
    second=upload(c,case,capture_body(case,s,raw),raw).json()
    assert second['receipt']['duplicate_original'] and len(second['case']['media'])==1
    assert len(second['media']['captures'])==2 and second['session']['received_images']==2
    assert second['case']['revision']==case['revision']+1


@pytest.mark.parametrize('attack',['cross_case','sha','no_timezone','future','nan_sensor','fake_unit','path','invalid_image','sensor_duplicate'])
def test_device_metadata_and_cross_case_attacks(service,attack):
    c,store=service;a=new(c);b=new(c);raw=image();s=session(c,a)
    meta=capture_body(a,s,raw);name='test.png'
    if attack=='cross_case':a=b;meta['expected_case_revision']=b['revision']
    if attack=='sha':meta['original_sha256']='0'*64
    if attack=='no_timezone':meta['captured_at']='2026-09-28T12:00:00'
    if attack=='future':meta['captured_at']='2999-01-01T00:00:00Z'
    if attack in ('nan_sensor','fake_unit','sensor_duplicate'):
        sensor={'name':'x','value':1,'unit':'mm','source':'test'}
        if attack=='nan_sensor':sensor['value']=float('nan')
        if attack=='fake_unit':sensor['unit']='certified_authenticity'
        meta['sensors']=[sensor,sensor] if attack=='sensor_duplicate' else [sensor]
    if attack=='path':name='../test.png'
    if attack=='invalid_image':raw=b'not an image';meta['original_sha256']=hashlib.sha256(raw).hexdigest()
    r=upload(c,a,meta,raw,name)
    assert r.status_code==422,r.text
    assert not store.read('case',a['id'])['media']
    assert not store.listing('capture_receipt')


def test_case_version_expired_and_busy_gate(service):
    c,store=service;case=new(c);raw=image();s=session(c,case)
    case,_=photo(c,case)
    assert upload(c,case,capture_body(case,s,raw,expected_case_revision=1),raw).status_code==409
    with store.tx() as db:
        s['expires_at']=time.time()-1;store.put(db,'capture_session',s)
    assert upload(c,case,capture_body(case,s,raw),raw).status_code==410


def test_limits_are_atomic_and_replay_does_not_charge(service):
    c,store=service;case=new(c);raw=image();s=session(c,case,max_images=1,max_total_bytes=len(raw))
    body=capture_body(case,s,raw);first=upload(c,case,body,raw).json();case=first['case']
    assert upload(c,case,body,raw).json()==first
    assert upload(c,case,capture_body(case,s,raw),raw).status_code==413
    assert store.read('capture_session',s['id'])['received_images']==1
    assert len(store.read('case',case['id'])['media'][0]['captures'])==1
    other=new(c);small=session(c,other,max_total_bytes=len(raw)-1)
    assert upload(c,other,capture_body(other,small,raw),raw).status_code==413
    assert not store.read('case',other['id'])['media']


def test_concurrent_replay_produces_one_original_and_charge(service):
    c,store=service;case=new(c);raw=image();s=session(c,case);body=capture_body(case,s,raw)
    with ThreadPoolExecutor(max_workers=2) as pool:
        values=list(pool.map(lambda _:upload(c,case,body,raw),range(2)))
    assert all(v.status_code==201 for v in values) and values[0].json()==values[1].json()
    assert store.read('capture_session',s['id'])['received_images']==1


def test_session_budget_limits_and_no_vendor_claim(service):
    c,_=service;case=new(c)
    for _ in range(5):session(c,case)
    r=c.post('/api/cases/'+case['id']+'/capture-sessions',json=mut(case)|{'device':{'kind':'phone','label':'test'}})
    assert r.status_code==429
    r=c.get('/api/cases/'+case['id']+'/capture-sessions').json()
    assert not r['vendor_sdk_verified'] and all(not s['vendor_authenticated'] for s in r['sessions'])


@pytest.mark.parametrize('path',['risk-checks','risk-facts','capture-sessions','device-captures'])
def test_new_mutations_inherit_token_and_origin_gate(service,path):
    c,_=service;case=new(c);url='/api/cases/'+case['id']+'/'+path
    token=c.headers.pop('X-Cizheng-Token')
    assert c.post(url,json={}).status_code==403
    c.headers['X-Cizheng-Token']=token
    assert c.post(url,json={},headers={'Origin':'https://foreign.example'}).status_code==403


def test_bounded_multipart_rejects_duplicate_keys_parts_and_non_multipart():
    from cizheng.store import Problem
    with pytest.raises(Problem):parse_multipart('application/json',b'{}')
    with pytest.raises(Problem):parse_multipart('multipart/form-data; boundary=x',b'a'*(IMAGE_LIMIT+32769))
    raw=b'--x\r\nContent-Disposition: form-data; name="metadata"\r\n\r\n{}\r\n--x--\r\n'
    with pytest.raises(Problem):parse_multipart('multipart/form-data; boundary=x',raw)


def test_corrupt_original_is_obvious_conflict_and_cannot_be_overridden(service):
    c,store=service;case,_=photo(c,new(c));m=case['media'][0]
    with store.tx() as db:db.execute('UPDATE blobs SET bytes=? WHERE id=?',(b'corrupt',m['id']))
    r=c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert r['indices']['conflict_index']==15
    assert 'SHA256' in r['dimensions'][-1]['reasons'][0]
    assert check(c,case,'capture','consistent').status_code==409


def test_missing_model_observation_and_foreign_media_are_not_grounded(service):
    c,store=service;a,_=photo(c,new(c));b,_=photo(c,new(c),'red')
    model={'id':'synthetic','case_id':a['id'],'case_revision':a['revision'],'state':'ready',
           'observations':[{'id':'foreign','media_id':b['media'][0]['id'],'region':[0,0,1,1]}],
           'assessment':{'claims':[{'dimension':'period','status':'conflicting','conflict':['foreign'],'reasoning_summary':'test'}]}}
    assert triage(store,a,model)['indices']['conflict_index'] is None


def saved_current_conflict(store, case):
    """A saved software fixture, never a model invocation or expert label."""
    run = {'id': uid('run'), 'case_id': case['id'], 'case_revision': case['revision'],
           'state': 'ready', 'reference_snapshot': [],
           'observations': [{'id': 'fixture-obs', 'media_id': case['media'][0]['id'], 'region': [0, 0, 1, 1]}],
           'assessment': {'claims': [{'dimension': 'period', 'status': 'conflicting',
               'conflict': ['fixture-obs'], 'support': [], 'reasoning_summary': 'Synthetic recorded conflict'}]}}
    with store.tx() as db:
        store.put(db, 'run', run)
        case['current_run_id'] = run['id']
        store.put(db, 'case', case)
    return run


@pytest.mark.parametrize('dimension', ['period', 'condition'])
def test_review_only_revision_preserves_model_conflict_and_original_run(service, dimension):
    c, store = service; case, _ = photo(c, new(c)); run = saved_current_conflict(store, case)
    original = digest(store.read('run', run['id']))
    before = c.get('/api/cases/'+case['id']+'/risk-triage').json()
    response = check(c, case, dimension, 'consistent'); assert response.status_code == 201
    case = response.json()['case']
    after = c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert before['material_context_sha256'] == after['material_context_sha256']
    assert after['assessment_run_id'] == run['id']
    assert after['dimensions'][0]['state'] == 'conflicting'
    assert after['indices']['conflict_index'] == 20
    assert digest(store.read('run', run['id'])) == original
    # Consecutive review-only mutations cannot silently remove the same conflict.
    response = check(c, case, 'style', 'consistent'); assert response.status_code == 201
    assert c.get('/api/cases/'+case['id']+'/risk-triage').json()['indices']['conflict_index'] == 20


def test_material_edit_invalidates_review_only_model_bridge(service):
    c, store = service; case, _ = photo(c, new(c)); saved_current_conflict(store, case)
    case = check(c, case, 'condition', 'consistent').json()['case']
    # A new pinned material statement changes the basis, even when it is not a conflict.
    case = fact(c, case, 'height_mm', 300, 301).json()['case']
    after = c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert after['assessment_run_id'] is None
    assert after['dimensions'][0]['state'] == 'unknown'
    assert after['indices']['coverage_weight'] == 0


def test_reverting_material_text_does_not_revive_historical_model_basis(service):
    c, store = service; case, _ = photo(c, new(c)); saved_current_conflict(store, case)
    case = check(c, case, 'condition', 'consistent').json()['case']
    original = copy.deepcopy(case['catalogue'])
    changed = original | {'dimensions': 'Synthetic changed registration'}
    for catalogue in (changed, original):
        response = c.patch('/api/cases/'+case['id']+'/catalogue',
            json=mut(case)|{'workflow': case['workflow'], 'catalogue': catalogue})
        assert response.status_code == 200
        case = response.json()
    after = c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert after['assessment_run_id'] is None
    assert after['dimensions'][0]['state'] == 'unknown'
    case = check(c, case, 'condition', 'consistent').json()['case']
    assert c.get('/api/cases/'+case['id']+'/risk-triage').json()['assessment_run_id'] is None


def txt_attachment(c, case):
    response = c.post('/api/cases/'+case['id']+'/evidence-documents', json=mut(case)|{
        'filename': 'synthetic-source.txt', 'file_base64': base64.b64encode(b'Software fixture source').decode(),
        'source': 'synthetic test', 'rights_note': 'generated test text', 'permission': 'local_use_authorized'})
    assert response.status_code in (200, 201)
    return response.json()['case']


def test_superseded_source_dispute_is_history_not_current_conflict(service):
    c, store = service; case, _ = photo(c, new(c)); case = txt_attachment(c, case)
    doc = case['evidence_documents'][0]
    event = {'event_type': 'statement', 'status': 'disputed', 'date_text': '2000',
             'party': 'synthetic', 'place': 'synthetic', 'description': 'Test dispute',
             'object_link_basis': 'synthetic fixture',
             'evidence': [{'kind': 'attachment', 'document_id': doc['id'], 'locator': 'line 1'}]}
    url = '/api/cases/'+case['id']+'/provenance-events'
    response = c.post(url, json=mut(case)|event); assert response.status_code in (200, 201)
    case = response.json()['case']; old = case['provenance_events'][-1]['id']
    assert c.get('/api/cases/'+case['id']+'/risk-triage').json()['indices']['conflict_index'] == 20
    response = c.post(url, json=mut(case)|event|{'status': 'documented', 'supersedes': old, 'description': 'Corrected fixture'})
    assert response.status_code in (200, 201)
    case = response.json()['case']; after = c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert after['dimensions'][3]['state'] == 'unknown'
    assert len(case['provenance_events']) == 2
    assert case['provenance_events'][0]['id'] == old


def test_attachment_corruption_invalidates_saved_evaluation(service):
    c, store = service; case, _ = photo(c, new(c)); case = txt_attachment(c, case)
    doc = case['evidence_documents'][0]
    body = mut(case)|{'dimension': 'provenance', 'state': 'consistent',
        'reason': 'Software fixture with source', 'next_evidence': 'Verify original',
        'evidence': [{'kind': 'attachment', 'id': doc['id'], 'sha256': doc['sha256'], 'locator': 'line 1'}]}
    response = c.post('/api/cases/'+case['id']+'/risk-checks', json=body); assert response.status_code == 201
    case = response.json()['case']
    with store.tx() as db:
        db.execute('UPDATE blobs SET bytes=? WHERE id=?', (b'corrupt test bytes', doc['artifact_id']))
    after = c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert after['dimensions'][3]['state'] == 'unknown'
    assert after['dimensions'][5]['state'] == 'conflicting'
    assert after['indices']['conflict_index'] == 15
    assert after['indices']['coverage_weight'] == 15


def test_corrected_fact_cannot_create_a_second_supersession_branch(service):
    c,_=service;case,_=photo(c,new(c));a=fact(c,case,'height_mm',300,301).json();case=a['case']
    case=fact(c,case,'height_mm',350,351,supersedes=a['fact']['id']).json()['case']
    assert fact(c,case,'height_mm',400,401,supersedes=a['fact']['id']).status_code==409


def test_native_metadata_duplicate_keys_and_transfer_encoding_are_rejected(service):
    c,_=service;case=new(c);raw=image();s=session(c,case);body=capture_body(case,s,raw)
    metadata=json.dumps(body)[:-1]+',"operator":"other"}'
    r=c.post('/api/cases/'+case['id']+'/device-captures',files={'metadata':(None,metadata),'file':('test.png',raw)})
    assert r.status_code==422


def test_capture_running_case_and_case_archive_limit(service):
    c,store=service;case=new(c);s=session(c,case);raw=image()
    with store.tx() as db:store.put(db,'run',{'id':uid('run'),'case_id':case['id'],'state':'running'})
    assert upload(c,case,capture_body(case,s,raw),raw).status_code==409
    with store.tx() as db:db.execute("DELETE FROM records WHERE kind='run'")
    case,_=photo(c,case)
    with store.tx() as db:
        saved=store.get(db,'case',case['id'])
        saved['media']=saved['media']*30
        store.put(db,'case',saved)
    other=image('red')
    assert upload(c,case,capture_body(case,s,other),other).status_code==413


def test_laya_default_stays_disabled_without_importing_or_loading_model():
    from integrations.laya_router.adapter import status
    result=status()
    assert not result['enabled'] and not result['can_override_priority_index'] and not result['executed_for_ceramics']


@pytest.mark.parametrize('facts',[{'image_base64':'fake'}, {'confidence':.99}, {'saved_photo_count':-1},
                                  {'unknown_dimensions':['authenticity']}, {'saved_photo_count':float('nan')}])
def test_disabled_laya_adapter_rejects_pixels_and_probability_as_routing_fact(facts):
    from integrations.laya_router.adapter import predict_local
    with pytest.raises(ValueError):
        predict_local('/does-not-exist',{'facts':facts,'incumbent_next_step':'request_evidence','review_required':True})


def test_auto_conflict_display_is_bounded_without_suppressing_rule_totals():
    from cizheng.risk_triage import obvious_conflicts
    facts=[{'id':str(i),'field':'height_mm','value_min':i*10+1,'value_max':i*10+2,
            'evidence':[],'supersedes':None} for i in range(100)]
    rows,totals=obvious_conflicts({'risk_facts':facts})
    assert totals['same_property_disjoint_height_mm']==4950
    assert len(rows)==10


@pytest.mark.parametrize('with_model', [False, True])
def test_material_revert_does_not_reactivate_old_operator_assertion(service, with_model):
    c, store = service; case, _ = photo(c, new(c))
    if with_model:
        saved_current_conflict(store, case)
    case = check(c, case, 'period', 'consistent').json()['case']
    old_check = copy.deepcopy(case['risk_checks'][0])
    original = copy.deepcopy(case['catalogue'])
    for catalogue in (original | {'dimensions': 'Changed fixture material'}, original):
        response = c.patch('/api/cases/'+case['id']+'/catalogue',
            json=mut(case)|{'workflow': case['workflow'], 'catalogue': catalogue})
        assert response.status_code == 200
        case = response.json()
        triaged = c.get('/api/cases/'+case['id']+'/risk-triage').json()
        assert triaged['dimensions'][0]['state'] == 'unknown'
        assert triaged['indices']['coverage_weight'] == 0
        assert old_check['id'] not in triaged['current_material_check_ids']
    assert case['risk_checks'] == [old_check]
    # A new check may evaluate its own dimension; it cannot reactivate the historical period check.
    case = check(c, case, 'condition', 'consistent').json()['case']
    triaged = c.get('/api/cases/'+case['id']+'/risk-triage').json()
    assert triaged['dimensions'][0]['state'] == 'unknown'
    assert triaged['dimensions'][4]['state'] == 'consistent'
    assert triaged['indices']['coverage_weight'] == 15
    assert old_check['id'] not in triaged['current_material_check_ids']
    assert case['risk_checks'][0] == old_check
